### ISSUE TITLE
Flow: unkown query parameters can't be matched

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/laxar#468] opened 2017-06-16 13:42 UTC
Any unkown query parameters can't be matched: `Got no unknownPlace redirect and no default place. Doing nothing.`

Router configuration with `navigo.useHash: true` and `query.enabled` either `true` or `false`.

**Comment by x1B** [comment] 2017-06-16 13:49
This problem can apparently be reproduced by having a place with pattern `/` and entering through `debug.html#/` (works) or `debug.html#/?a=b` (does not work).

Of course, this assumes that query parameters should have no impact on routing.

**Comment by x1B** [comment] 2017-06-16 13:55
Did some more research:

 - apparently, the problem happens only if the routing URL (before query) is exactly `/`
 - routing a URL such as `/browse?x=y` (shop-demo) seems to work OK; it behaves just like `/browse` without query, as intended.

**Comment by alex3683** [comment] 2017-06-21 09:25
Fixed on `master` (`v2.0.0`).

**Closed by alex3683** 2017-06-21 09:25 UTC
Labels: epic: runtime, state: in progress, type: bug, version: 2.x
